# Generated by Django 5.0.7 on 2024-08-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe_description_ingredient_recipe_ingredients_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
    ]
